### ISSUE TITLE
Unable to compile the code

### ISSUE THREAD

**Issue by ucganesh** [jbarrez/activiti-spring-boot-webinar#2]
Hi Barrez,

I am unable to compile the code, as the maven dependencies could not be resolved. Are the artifacts of spring boot with group id org.activiti available in any repository?

Can these artifacts be used in applications for production usage?

Thanks
Chaitanya

**Comment by jbarrez** [comment]
Fixed in https://github.com/jbarrez/activiti-spring-boot-webinar/commit/325754c387cc9fb40c8985fee26190c5c4c68437

See the new readme on how to build it: https://github.com/jbarrez/activiti-spring-boot-webinar/blob/master/README.md

**Comment by ucganesh** [comment]
Thanks for the guidelines, it helps
